"""Generates one reference page per n8n workflow, from the committed workflow JSON.

The gap this closes: WF-12 had a single ASCII sketch that **contradicted** what was deployed,
WF-18 had three sentences, and WF-00 had one paragraph. There was no way to know what a
workflow actually does without opening the n8n canvas.

    python -m grace_platform.docs.gen_workflows           write
    python -m grace_platform.docs.gen_workflows --check   exit 1 if anything would change
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
WORKFLOWS = ROOT / "platform" / "n8n" / "workflows"
OUT = ROOT / "Docs" / "generated" / "workflows"

BANNER = (
    "<!-- GENERATED by grace_platform.docs.gen_workflows — DO NOT EDIT.\n"
    "     Source of truth: platform/n8n/workflows/*.json\n"
    "     Regenerate with: make docs -->"
)

#: Live ids, so a page points at the thing you can actually open.
LIVE_IDS: dict[str, str] = {
    "WF-00": "TskMxWsdNPdtyzwz",
    "WF-12": "Nig7UzGSTwVZuFLg",
    "WF-18": "IvXEhYoHdxT3e7oA",
}

#: One line per workflow on whether it can currently do anything.
STATUS: dict[str, str] = {
    "WF-00": "**Active.** Fires whenever any other workflow errors.",
    "WF-12": (
        "**Published but dormant.** Nothing triggers it yet — the signed webhook that would "
        "comes from Core API, which is not built. Correct scaffolding, currently inert."
    ),
    "WF-18": (
        "**Published but dormant.** Called only by WF-12, which is itself dormant. It also "
        "stops short of placing a voice call — that needs Phase F (A-20)."
    ),
    "WF-20": "**Active.** Runs daily against Vapi's call API. Works today, no Core API needed.",
    "WF-21": "**Active.** Runs weekly against Vapi's call API. Works today.",
    "WF-22": "**Active.** Runs hourly against Vapi's call API. Works today.",
}

NODE_KIND = {
    "n8n-nodes-base.webhook": "Webhook trigger",
    "n8n-nodes-base.scheduleTrigger": "Schedule trigger",
    "n8n-nodes-base.errorTrigger": "Error trigger",
    "n8n-nodes-base.executeWorkflowTrigger": "Called by another workflow",
    "n8n-nodes-base.executeWorkflow": "Calls another workflow",
    "n8n-nodes-base.httpRequest": "HTTP request",
    "n8n-nodes-base.code": "Code",
    "n8n-nodes-base.if": "Branch (if)",
    "n8n-nodes-base.switch": "Branch (switch)",
    "n8n-nodes-base.wait": "Wait",
    "n8n-nodes-base.respondToWebhook": "Respond to webhook",
    "n8n-nodes-base.dataTable": "Data Table",
    "n8n-nodes-base.postgres": "Postgres",
}


def _node_summary(node: dict[str, Any]) -> str:
    """One sentence on what this node does, derived from its actual settings."""
    t, p = node["type"], node.get("parameters", {})

    if t == "n8n-nodes-base.webhook":
        raw = " Raw Body on." if p.get("options", {}).get("rawBody") else ""
        return f"Receives `{p.get('httpMethod', '?')} /{p.get('path', '?')}`.{raw}"
    if t == "n8n-nodes-base.scheduleTrigger":
        rule = json.dumps(p.get("rule", {}))
        return f"Runs on a schedule ({p.get('timezone', 'no timezone set')}). `{rule[:80]}`"
    if t == "n8n-nodes-base.errorTrigger":
        return "Fires when any workflow listing this one as its error handler fails."
    if t == "n8n-nodes-base.executeWorkflowTrigger":
        return f"Entry point when another workflow calls this one (`{p.get('inputSource', '?')}`)."
    if t == "n8n-nodes-base.executeWorkflow":
        return f"Invokes workflow `{p.get('workflowId', '?')}`."
    if t == "n8n-nodes-base.httpRequest":
        url = str(p.get("url", "?"))
        url = re.sub(r"\{\{\s*\$env\.(\w+)\s*\}\}", r"$\1", url).replace("=", "", 1)
        return f"`{p.get('method', 'GET')}` to `{url}`, timeout {p.get('options', {}).get('timeout', '?')} ms."
    if t == "n8n-nodes-base.code":
        first = next(
            (
                ln.strip().lstrip("/ ").strip()
                for ln in str(p.get("jsCode", "")).splitlines()
                if ln.strip().startswith("//")
            ),
            "",
        )
        return first or "Runs JavaScript to transform the data."
    if t == "n8n-nodes-base.if":
        return "Splits into a true branch and a false branch."
    if t == "n8n-nodes-base.switch":
        keys = [r.get("outputKey", "?") for r in p.get("rules", {}).get("values", [])]
        fallback = p.get("options", {}).get("renameFallbackOutput")
        return "Routes to: " + ", ".join(f"`{k}`" for k in [*keys, fallback] if k) + "."
    if t == "n8n-nodes-base.wait":
        return (
            f"Pauses {p.get('amount', '?')} {p.get('unit', '')}. Over 65s, so the execution is "
            "written to the database and survives a restart."
        )
    if t == "n8n-nodes-base.respondToWebhook":
        return f"Replies HTTP {p.get('responseCode', 200)} and ends the request."
    if t == "n8n-nodes-base.dataTable":
        return f"Writes a row to the `{p.get('tableId', '?')}` data table."
    if t == "n8n-nodes-base.postgres":
        return "Writes a permanent record to Postgres."
    return "—"


def _mermaid(wf: dict[str, Any]) -> str:
    ids = {n["name"]: f"n{i}" for i, n in enumerate(wf["nodes"])}
    lines = ["```mermaid", "flowchart TD"]
    for name, nid in ids.items():
        node = next(n for n in wf["nodes"] if n["name"] == name)
        shape = "([{}])" if "Trigger" in NODE_KIND.get(node["type"], "") else "[{}]"
        label = name.replace('"', "'")
        disabled = " 🚫" if node.get("disabled") else ""
        lines.append(f"    {nid}{shape.format(label + disabled)}")
    for src, conn in wf.get("connections", {}).items():
        if src not in ids:
            continue
        for branch_i, branch in enumerate(conn.get("main", [])):
            for target in branch:
                if target["node"] in ids:
                    label = f"|{branch_i}| " if len(conn.get("main", [])) > 1 else ""
                    lines.append(f"    {ids[src]} -->{label}{ids[target['node']]}")
    lines.append("```")
    return "\n".join(lines)


def render(path: Path) -> tuple[str, str]:
    wf = json.loads(path.read_text(encoding="utf-8"))
    name = str(wf["name"])
    wf_id = name.split(" ")[0]
    live = LIVE_IDS.get(wf_id, "")

    rows = ["| # | Node | Kind | What it does | Credential |", "|---|---|---|---|---|"]
    for i, node in enumerate(wf["nodes"], start=1):
        creds = ", ".join(f"`{c.get('id', '?')}`" for c in (node.get("credentials") or {}).values())
        flag = " *(disabled)*" if node.get("disabled") else ""
        rows.append(
            f"| {i} | **{node['name']}**{flag} | {NODE_KIND.get(node['type'], node['type'])} | "
            f"{_node_summary(node)} | {creds or '—'} |"
        )

    settings = wf.get("settings", {})
    err = settings.get("errorWorkflow", "—")

    body = f"""{BANNER}

# {name}

**Status:** {STATUS.get(wf_id, "—")}
**Source:** `platform/n8n/workflows/{path.name}`
**Error handler:** `{err}`

## Flow

{_mermaid(wf)}

## Nodes, in order

{chr(10).join(rows)}

## Where to see it

n8n → **Workflows** → `[dev] {name}`{f" (`{live}`)" if live else ""}.
Tagged `managed:git` and `env:dev`, which is how the deploy script knows it owns it — anything
untagged is invisible to it.

Runs appear under **Executions**.
"""
    return f"{wf_id}.md", body


def render_index(pages: dict[str, str]) -> str:
    rows = ["| Workflow | Status |", "|---|---|"]
    for fname in sorted(pages):
        if fname == "README.md":
            continue
        wf_id = fname.removesuffix(".md")
        rows.append(f"| [{wf_id}]({fname}) | {STATUS.get(wf_id, '—')} |")

    return f"""{BANNER}

# n8n workflows

n8n handles everything that happens **after** a call — notifications, escalation timing, and
reporting. It is never on the call path: nothing a caller waits for touches n8n.

{chr(10).join(rows)}

Instance: `palmleafmassage.app.n8n.cloud`. One account serves both environments, separated by
the `[dev]` / `[prod]` name prefix and the `env:*` tag.
"""


def build() -> dict[str, str]:
    pages = dict(render(p) for p in sorted(WORKFLOWS.glob("*.json")))
    pages["README.md"] = render_index(pages)
    return pages


def main() -> int:
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    pages = build()
    stale: list[str] = []

    for name, content in pages.items():
        path = OUT / name
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        if check:
            stale.append(f"{'missing' if existing is None else 'stale  '}: workflows/{name}")
        else:
            path.write_text(content, encoding="utf-8")

    for path in OUT.glob("*.md"):
        if path.name not in pages:
            if check:
                stale.append(f"orphan : workflows/{path.name}")
            else:
                path.unlink()

    if check and stale:
        print("\n✗ generated workflow docs are out of date:\n", file=sys.stderr)
        for s in stale:
            print(f"    {s}", file=sys.stderr)
        print("\n  Run: make docs\n", file=sys.stderr)
        return 1

    print(f"✓ {len(pages)} workflow page(s) {'up to date' if check else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
