"""Generates one reference page per Vapi tool, from the code that defines it.

The gap this closes: of 15 tools, exactly one had any written detail, split across three
documents, with its parameters shown as an elided comment. There was nowhere to look up what a
tool's parameters mean or how it is configured.

These pages are generated from `TOOL_REGISTRY`, the generated tool JSON, and `.lock.json`, so
they cannot drift from what is deployed. CI fails if they are stale.

    python -m grace_platform.docs.gen_tools           write
    python -m grace_platform.docs.gen_tools --check   exit 1 if anything would change
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from grace_contracts import HAND_AUTHORED_TOOLS, TOOL_REGISTRY, ToolSpec

ROOT = Path(__file__).resolve().parents[3]
TOOLS_JSON = ROOT / "platform" / "vapi" / "tools"
LOCK = ROOT / "platform" / "vapi" / ".lock.json"
OUT = ROOT / "Docs" / "generated" / "tools"

BANNER = (
    "<!-- GENERATED by grace_platform.docs.gen_tools — DO NOT EDIT.\n"
    "     Source of truth: src/grace_contracts/tools/registry.py and the generated tool JSON.\n"
    "     Regenerate with: make docs -->"
)

#: Prose for the hand-authored Vapi tool types, which have no Pydantic model to read.
HAND_AUTHORED_DOCS: dict[str, dict[str, str]] = {
    "transferToHuman": {
        "purpose": "Transfers the caller to a person at the front desk.",
        "when": (
            "Immediately after `flagEscalation`, every single time. The prompt requires the pair "
            "in that order."
        ),
        "note": (
            "This is a Vapi `transferCall` tool, not a function tool, so **it takes no "
            "parameters at all** — its DTO has no `function` property. That is precisely why "
            "`flagEscalation` exists: it is the only way context reaches the person answering.\n\n"
            "`destinations` is deliberately empty, which makes Vapi ask our server for the "
            "destination via the `transfer-destination-request` webhook. The server decides the "
            "number, the caller ID to present, and the whisper text at that moment."
        ),
    },
    "endCall": {
        "purpose": "Hangs up.",
        "when": "Once the caller has what they need and the conversation has closed naturally.",
        "note": (
            "A Vapi `endCall` tool. This used to be the assistant flag `endCallFunctionEnabled`, "
            "which **no longer exists** on `CreateAssistantDTO` — verified 2026-08-03. Hanging up "
            "is an explicit registered tool now."
        ),
    },
}


def _lock() -> dict[str, Any]:
    return json.loads(LOCK.read_text(encoding="utf-8")) if LOCK.exists() else {}


def _describe_type(schema: dict[str, Any]) -> str:
    if "enum" in schema:
        return " · ".join(f"`{v}`" for v in schema["enum"])
    t = schema.get("type", "?")
    bits = [f"`{t}`"]
    if "minLength" in schema or "maxLength" in schema:
        lo, hi = schema.get("minLength"), schema.get("maxLength")
        bits.append(f"length {lo or 0}–{hi or '∞'}")
    if "minimum" in schema or "maximum" in schema:
        bits.append(f"{schema.get('minimum', '−∞')}–{schema.get('maximum', '∞')}")
    if "pattern" in schema:
        bits.append(f"pattern `{schema['pattern']}`")
    return ", ".join(bits)


def _params_table(params: dict[str, Any]) -> str:
    props: dict[str, Any] = params.get("properties", {})
    required = set(params.get("required", []))
    if not props:
        return "_This tool takes no parameters._\n"

    rows = [
        "| Parameter | Type / allowed values | Required | Default | What it means |",
        "|---|---|---|---|---|",
    ]
    for name, spec in props.items():
        default = spec.get("default")
        default_s = "—" if default is None else f"`{json.dumps(default)}`"
        desc = str(spec.get("description", "—")).replace("|", "\\|")
        rows.append(
            f"| `{name}` | {_describe_type(spec)} | "
            f"{'**yes**' if name in required else 'no'} | {default_s} | {desc} |"
        )
    strict = params.get("additionalProperties") is False
    table = "\n".join(rows)
    if strict:
        table += (
            "\n\nAny parameter not listed above is **rejected**, not ignored — the model "
            "inventing a field must be a loud error, never silent."
        )
    return table + "\n"


def _settings_table(spec: ToolSpec, tool: dict[str, Any], tool_id: str) -> str:
    server = tool.get("server", {})
    backoff = server.get("backoffPlan")
    rows = [
        "| Setting | Value | Why |",
        "|---|---|---|",
        f"| Runs in background | {'**yes**' if spec.is_async else 'no'} | "
        + (
            "Vapi resolves it immediately and never returns the result to the model"
            if spec.is_async
            else "Grace waits for the answer before speaking"
        )
        + " |",
        f"| Changes data | {'**yes**' if spec.is_write else 'no'} | "
        + (
            "Must be idempotent on `callId:toolCallId` (I3)"
            if spec.is_write
            else "Safe to call repeatedly"
        )
        + " |",
        f"| p95 target | {f'{spec.budget_ms} ms' if spec.budget_ms else '—'} | "
        "A target for alerting, **not** a deadline — the deadline is `GRACE_TOOL_DEADLINE_MS` |",
        f"| Request timeout | {server.get('timeoutSeconds', '—')} s | "
        "Above our own deadline, so our graceful sentence fires first |",
        f"| Retry | {'1 retry, fixed 1s' if backoff else '**none**'} | "
        + (
            "Read-only, so retrying is safe"
            if backoff
            else "A retried write is a real duplicate — a second booking, a second text"
        )
        + " |",
    ]
    if tool_id:
        rows.append(f"| Live Vapi ID | `{tool_id}` | Vapi dashboard → **Tools** |")
    return "\n".join(rows) + "\n"


def _speech_section(tool: dict[str, Any], spec: ToolSpec) -> str:
    msgs = {m.get("type"): m.get("content", "") for m in tool.get("messages", [])}
    lines = []
    if start := msgs.get("request-start"):
        lines.append(f'- **While it runs:** "{start}"')
    if failed := msgs.get("request-failed"):
        lines.append(f'- **If it fails:** "{failed}"')
    if not lines:
        if spec.acked_by_next_tool:
            return (
                "Deliberately silent. The prompt requires `transferToHuman` immediately after "
                "this tool, and that speaks — two acknowledgements in a row would be worse than "
                "none.\n"
            )
        return "_Nothing spoken; Grace phrases the result herself._\n"
    return "\n".join(lines) + "\n"


def render_generated(spec: ToolSpec, tool: dict[str, Any], tool_id: str) -> str:
    params = tool.get("function", {}).get("parameters", {})
    kind = "background task" if spec.is_async else "question Grace waits on"

    return f"""{BANNER}

# `{spec.name}`

**Kind:** function tool — a {kind}
**Source model:** `{spec.input_model.__module__}.{spec.input_model.__name__}`
**Generated JSON:** `platform/vapi/tools/{spec.name}.json`

## What it does, and when Grace calls it

{spec.description}

## Parameters

{_params_table(params)}
## Settings

{_settings_table(spec, tool, tool_id)}
## What the caller hears

{_speech_section(tool, spec)}
## Where to see it

Vapi dashboard → **Tools** → `{spec.name}`{f" (`{tool_id}`)" if tool_id else ""}.
It is attached to the assistant under **Assistants** → *Grace — PalmLeaf [dev]* → *Tools*.
"""


def render_hand_authored(name: str, tool: dict[str, Any], tool_id: str) -> str:
    doc = HAND_AUTHORED_DOCS[name]
    msgs = {m.get("type"): m.get("content", "") for m in tool.get("messages", [])}
    spoken = f'- **When triggered:** "{msgs["request-start"]}"' if "request-start" in msgs else "—"

    return f"""{BANNER}

# `{name}`

**Kind:** Vapi `{tool.get("type")}` tool — hand-authored, no schema source
**Source:** `platform/vapi/tools/{name}.json`

## What it does, and when Grace calls it

{doc["purpose"]}

{doc["when"]}

## Parameters

_None._ {doc["note"]}

## What the caller hears

{spoken}

## Where to see it

Vapi dashboard → **Tools** → type `{tool.get("type")}`{f" (`{tool_id}`)" if tool_id else ""}.
"""


def render_index(tool_ids: dict[str, str]) -> str:
    rows = [
        "| Tool | Kind | Waits? | Changes data? | p95 |",
        "|---|---|---|---|---|",
    ]
    for spec in TOOL_REGISTRY:
        rows.append(
            f"| [`{spec.name}`]({spec.name}.md) | function | "
            f"{'background' if spec.is_async else 'yes'} | "
            f"{'**yes**' if spec.is_write else 'no'} | "
            f"{f'{spec.budget_ms} ms' if spec.budget_ms else '—'} |"
        )
    for name in HAND_AUTHORED_TOOLS:
        rows.append(f"| [`{name}`]({name}.md) | Vapi tool type | — | — | — |")

    total = len(TOOL_REGISTRY) + len(HAND_AUTHORED_TOOLS)
    return f"""{BANNER}

# Grace's tools

{total} tools: {len(TOOL_REGISTRY)} generated from the Pydantic registry, and
{len(HAND_AUTHORED_TOOLS)} hand-authored Vapi tool types that take no parameters.

A tool is Grace's **only** way to learn a fact or change something. She decides *when* to call
one; the server decides *what the answer is*. She may never state a fact that did not come from
a tool result.

{chr(10).join(rows)}

Assistant: *Grace — PalmLeaf [dev]* (`{tool_ids.get("__assistant__", "not deployed")}`).
"""


def build() -> dict[str, str]:
    lock = _lock()
    tool_ids: dict[str, str] = dict(lock.get("toolIds", {}))
    pages: dict[str, str] = {}

    for spec in TOOL_REGISTRY:
        path = TOOLS_JSON / f"{spec.name}.json"
        if not path.exists():
            continue
        tool = json.loads(path.read_text(encoding="utf-8"))
        pages[f"{spec.name}.md"] = render_generated(spec, tool, tool_ids.get(spec.name, ""))

    for name in HAND_AUTHORED_TOOLS:
        path = TOOLS_JSON / f"{name}.json"
        if not path.exists():
            continue
        tool = json.loads(path.read_text(encoding="utf-8"))
        # transferToHuman is registered in Vapi under its type, `transferCall`.
        lookup = "transferCall" if name == "transferToHuman" else name
        pages[f"{name}.md"] = render_hand_authored(name, tool, tool_ids.get(lookup, ""))

    pages["README.md"] = render_index({"__assistant__": lock.get("assistantId", "")})
    return pages


def main() -> int:
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    pages = build()
    stale: list[str] = []

    for name, content in pages.items():
        path = OUT / name
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing == content:
            continue
        if check:
            stale.append(f"{'missing' if existing is None else 'stale  '}: tools/{name}")
        else:
            path.write_text(content, encoding="utf-8")

    for path in OUT.glob("*.md"):
        if path.name not in pages:
            if check:
                stale.append(f"orphan : tools/{path.name}")
            else:
                path.unlink()

    if check and stale:
        print("\n✗ generated tool docs are out of date:\n", file=sys.stderr)
        for s in stale:
            print(f"    {s}", file=sys.stderr)
        print("\n  Run: make docs\n", file=sys.stderr)
        return 1

    print(f"✓ {len(pages)} tool page(s) {'up to date' if check else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
