/**
 * Assembles platform/vapi/prompts/system.md from prompts/sections/*.md, injecting a
 * generated TOOLS section so the prompt cannot drift from the actual tool registry.
 *
 *   pnpm platform:vapi:prompt           write system.md
 *   pnpm platform:vapi:prompt --check   exit 1 if it would change (CI / T1)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { HAND_AUTHORED_TOOLS, TOOL_REGISTRY } from '@grace/contracts';

const PROMPTS_DIR = join(import.meta.dirname, 'prompts');
const SECTIONS_DIR = join(PROMPTS_DIR, 'sections');
const OUT = join(PROMPTS_DIR, 'system.md');

/** Where the generated tools table is spliced in — sections sort numerically around it. */
const TOOLS_SECTION_ORDER = '30';

function buildToolsSection(): string {
  const lines = [
    '## TOOLS',
    '',
    'These are the only ways you can learn a fact or change anything. If none of them covers what',
    'the caller needs, you do not know and cannot do it — escalate.',
    '',
    '| Tool | Call it when | Never |',
    '|---|---|---|',
  ];

  // Second sentence onward of each description is the "never" guidance; keep the table
  // readable by splitting on the first sentence boundary.
  for (const t of TOOL_REGISTRY) {
    const [first = '', ...rest] = t.description.split(/(?<=\.)\s+/);
    const when = first.trim();
    const never = rest.join(' ').trim() || '—';
    lines.push(`| \`${t.name}\` | ${when} | ${never} |`);
  }

  for (const name of HAND_AUTHORED_TOOLS) {
    lines.push(
      `| \`${name}\` | Connect the caller to a person, ALWAYS immediately after \`flagEscalation\`. | Never call this without calling \`flagEscalation\` first. |`,
    );
  }

  lines.push(
    '',
    'Tools that send a text (`sendIntakeForm`, `sendDepositLink`, `sendBookingConfirmation`) and',
    '`flagEscalation` complete in the background. Say what you said you would do and move on — do not',
    'wait for them and do not promise they have already arrived.',
    '',
  );
  return lines.join('\n');
}

function assemble(): string {
  const files = readdirSync(SECTIONS_DIR)
    .filter((f) => f.endsWith('.md'))
    .sort();

  const parts: string[] = [
    '<!-- GENERATED by platform/vapi/build-prompt.ts — DO NOT EDIT.',
    '     Edit prompts/sections/*.md instead. The TOOLS table is generated from',
    '     the registry in @grace/contracts and cannot be hand-edited. -->',
    '',
  ];

  let toolsInjected = false;
  for (const file of files) {
    // Splice the generated TOOLS block into its numeric slot.
    if (!toolsInjected && file.slice(0, 2) > TOOLS_SECTION_ORDER) {
      parts.push(buildToolsSection());
      toolsInjected = true;
    }
    parts.push(readFileSync(join(SECTIONS_DIR, file), 'utf8').trim(), '');
  }
  if (!toolsInjected) parts.push(buildToolsSection());

  return `${parts.join('\n').trimEnd()}\n`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const next = assemble();

  let current: string | null = null;
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* not yet generated */
  }

  if (check) {
    if (current !== next) {
      console.error('✗ prompts/system.md is out of date. Run: pnpm platform:vapi:prompt');
      process.exit(1);
    }
    console.log(`✓ system.md up to date (${String(next.length)} chars)`);
    return;
  }

  writeFileSync(OUT, next, 'utf8');
  console.log(`✓ wrote prompts/system.md (${String(next.length)} chars)`);
}

main();
