"""Assembles platform/vapi/prompts/system.md from prompts/sections/*.md.

The TOOLS section is generated from the registry, so the prompt cannot drift from the
actual tools — it can neither describe a tool that does not exist nor miss one that does.

    python -m grace_platform.vapi.build_prompt           write system.md
    python -m grace_platform.vapi.build_prompt --check   exit 1 if it would change
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from grace_contracts import HAND_AUTHORED_TOOLS, TOOL_REGISTRY

PROMPTS = Path(__file__).resolve().parents[3] / "platform" / "vapi" / "prompts"
SECTIONS = PROMPTS / "sections"
OUT = PROMPTS / "system.md"

TOOLS_SECTION_ORDER = "30"

_HAND_AUTHORED_ROWS = {
    "transferToHuman": (
        "Connect the caller to a person, ALWAYS immediately after `flagEscalation`.",
        "Never call this without calling `flagEscalation` first.",
    ),
    "endCall": (
        "End the call once the caller has what they need and has said goodbye.",
        "Never end a call while a question is unanswered — escalate instead.",
    ),
}


def build_tools_section() -> str:
    lines = [
        "## TOOLS",
        "",
        "These are the only ways you can learn a fact or change anything. If none of them covers what",
        "the caller needs, you do not know and cannot do it — escalate.",
        "",
        "| Tool | Call it when | Never |",
        "|---|---|---|",
    ]
    for t in TOOL_REGISTRY:
        # First sentence is "when"; the rest is the guardrail.
        parts = re.split(r"(?<=\.)\s+", t.description, maxsplit=1)
        when = parts[0].strip()
        never = parts[1].strip() if len(parts) > 1 else "—"
        lines.append(f"| `{t.name}` | {when} | {never} |")

    for name in HAND_AUTHORED_TOOLS:
        when, never = _HAND_AUTHORED_ROWS[name]
        lines.append(f"| `{name}` | {when} | {never} |")

    lines += [
        "",
        "Tools that send a text (`sendIntakeForm`, `sendDepositLink`, `sendBookingConfirmation`) and",
        "`flagEscalation` complete in the background. Say what you said you would do and move on — do not",
        "wait for them and do not promise they have already arrived.",
        "",
    ]
    return "\n".join(lines)


def assemble() -> str:
    files = sorted(p for p in SECTIONS.iterdir() if p.suffix == ".md")
    parts = [
        "<!-- GENERATED by grace_platform.vapi.build_prompt — DO NOT EDIT.",
        "     Edit prompts/sections/*.md instead. The TOOLS table is generated from",
        "     the registry in grace_contracts and cannot be hand-edited. -->",
        "",
    ]
    injected = False
    for path in files:
        if not injected and path.name[:2] > TOOLS_SECTION_ORDER:
            parts.append(build_tools_section())
            injected = True
        parts.append(path.read_text(encoding="utf-8").strip())
        parts.append("")
    if not injected:
        parts.append(build_tools_section())
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv
    nxt = assemble()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None

    if check:
        if current != nxt:
            print("✗ prompts/system.md is out of date. Run: make vapi-prompt", file=sys.stderr)
            return 1
        print(f"✓ system.md up to date ({len(nxt)} chars)")
        return 0

    OUT.write_text(nxt, encoding="utf-8")
    print(f"✓ wrote prompts/system.md ({len(nxt)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
