"""Web-call harness config + static server (03-vapi-layer §10).

    python -m grace_platform.vapi.harness            # generate config, serve on :4243
    python -m grace_platform.vapi.harness --generate  # generate config only

The harness page is the only channel that can talk to Grace until a number is live, and it
needs two values the page itself must not hard-code: the browser-safe **public** key and the
**deployed** assistant id. The id comes from ``.lock.json`` rather than a hand-typed value —
the same reasoning as ``deploy.locked_assistant_id``: the only id certainly real is the one
the last apply recorded.

``harness-config.js`` is gitignored. It is regenerated here rather than committed so the
assistant id can never go stale against the instance, and so the key stays out of the repo.

The TypeScript original (``pnpm platform:vapi:harness``) was dropped in the Python port; this
restores it. The browser page stays JavaScript because it runs in a browser.
"""

from __future__ import annotations

import argparse
import functools
import http.server
import json
import os
import socketserver
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[3] / "platform" / "vapi"
HARNESS_DIR = HERE / "web-harness"
CONFIG_PATH = HARNESS_DIR / "harness-config.js"
LOCK_PATH = HERE / ".lock.json"

DEFAULT_PORT = 4243


def generate() -> None:
    """Writes ``harness-config.js`` from ``.lock.json`` + ``VAPI_PUBLIC_KEY``."""
    public_key = os.environ.get("VAPI_PUBLIC_KEY", "").strip()
    if not public_key:
        sys.exit(
            "✗ VAPI_PUBLIC_KEY is not set — the browser SDK cannot start a call without it.\n"
            "  It is NOT the private VAPI_API_KEY: find it in the Vapi dashboard under\n"
            "  API Keys → Public Key, then add it to .env:\n"
            "      VAPI_PUBLIC_KEY=<the public key>"
        )

    if not LOCK_PATH.exists():
        sys.exit(
            "✗ platform/vapi/.lock.json is missing — the harness talks to the DEPLOYED\n"
            "  assistant, so its id comes from a completed apply. Run:\n"
            "      make vapi-apply ENV=dev"
        )

    lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    assistant_id = str(lock.get("assistantId", "")).strip()
    if not assistant_id:
        sys.exit("✗ .lock.json has no assistantId — re-run `make vapi-apply ENV=dev` first.")

    CONFIG_PATH.write_text(
        "// GENERATED by grace_platform.vapi.harness — do not edit, do not commit.\n"
        f"export const PUBLIC_KEY = {json.dumps(public_key)};\n"
        f"export const ASSISTANT_ID = {json.dumps(assistant_id)};\n",
        encoding="utf-8",
    )
    print(f"  ✓ wrote {CONFIG_PATH.relative_to(HERE.parents[1])} (assistant {assistant_id})")


def serve(port: int) -> None:
    """Serves the harness directory. The SDK needs an http origin, not ``file://``."""
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(HARNESS_DIR))

    # Without this a restart inside TIME_WAIT fails with "Address already in use", which in
    # a test window reads as a broken harness rather than a socket still closing.
    class Server(socketserver.TCPServer):
        allow_reuse_address = True

    with Server(("127.0.0.1", port), handler) as httpd:
        print(f"\n  Grace web-call harness → http://localhost:{port}\n")
        print("  Grace should open with the recording disclosure (I7).")
        print("  Ctrl-C to stop.\n")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\n  stopped.\n")


def main() -> int:
    parser = argparse.ArgumentParser(prog="vapi-harness")
    parser.add_argument("--generate", action="store_true", help="write the config and exit")
    parser.add_argument("--port", type=int, default=int(os.environ.get("GRACE_HARNESS_PORT", 0)))
    args = parser.parse_args()

    generate()
    if not args.generate:
        serve(args.port or DEFAULT_PORT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
